Batch-Delete Invites (SST-12015)
tractionguest/guest-api pull request #89
Opened 2020-08-27 19:03 UTC by clrobinson-traction

### Description
Adding two new endpoints to support batch-deleting invites. Specifically, this is for the Appointments feature.

### Changelog
- New Model: `DeleteList`
- New Endpoint: `POST /invites/batch_delete`

### TODO
- New Endpoint: `GET /batches/:batch_id`
- Error responses for `POST /invites/batch_delete`

2020-08-27 21:40 UTC, tractionguest-integrations commented
<!--
  0 failure: 
  0 warning: 
  3 messages
  
  DangerID: danger-id-Danger;
-->



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  Remember to use the `Squash and Merge` button to merge for single PRs!
    Always remember, your final commit message needs to start with a wrike ticket like, `[#1234] Your commit message`.
  </td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Nice! You've specified a versioning label :+1:</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>

  <a href="https://tractionguest.stoplight.io/docs/guest-api/branches/feature/batch-delete-invites/openapi.yml" target="_blank">View docs for this page</a> <em>(You'll need to have access to see this version of the docs)</em>
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7bded5d874d0a9697cd6c4495f0ca77459e104ef
</p>

2020-09-01 15:13 UTC, baldys submitted a review, later dismissed

2020-09-08 19:52 UTC, stevenallen05 requested changes

2020-09-08 19:52 UTC, stevenallen05 commented on openapi.yml
> +        '404':
You'll probably want to change this to a wildcard:

```suggestion
        '4XX':
```

2020-09-08 19:52 UTC, stevenallen05 commented on openapi.yml
> +        '401':
This should be a wildcard, too:

```suggestion
        '4XX':
```

2020-09-08 19:52 UTC, stevenallen05 commented
Also, linting failed

2020-09-08 20:42 UTC, clrobinson-traction commented
@stevenallen05 Linting should be fixed now.

2020-09-09 17:07 UTC, baldys approved these changes

2020-11-12 18:44 UTC, brandonjmckay commented
@clrobinson-traction you have some conflicting files... 😭

2021-01-20 20:21 UTC, merged